name: publish-doc-condaenv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - pybind11 >= 2.10.4
  - cmake >=3.24.2
  - make
  - compilers
  - numpy
  - zlib
  - sphinx>=7.2.6
  - sphinx_rtd_theme>=1.3.0
  - sphinx-argparse
  - sphinx-toolbox>=3.7.0
#  - myst-parser>=2.0.0
#  - pip
#  - pip:
##    -  git+https://github.com/sphinx-toolbox/sphinx-licenseinfo
##    - sphinx-argparse
#    - sphinx-toolbox
##    - sphinx-licenseinfo
#
