name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' #pattern match

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build distribution
        run: |
          python3 -m pip install build
          python3 -mbuild

      - name: Upload distribution to PyPI 
        uses: pypa/gh-action-pypi-publish@v1.8.11