name: build-docs
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      CONDA_SOLVER: libmamba

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: publish-doc-condaenv
        environment-file: .github/resources/publish-doc-condaenv.yml
        #use-mamba: no

    - name: Conda list
      run: conda list

    - name: Install self
      run: python3 -mpip install .

    - name: Build documentation
      #NB: -W to turn warnings into errors:
      run: make html SPHINXOPTS="-W"
      working-directory: ./doc/

    - name: Check HTML links
      run: make linkcheck
      working-directory: ./doc/
